---
title: "1) Why R?"
author: "Jasmine Hughes"
date: "9/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What is R?

*  R is Open Source and free!
*  It is a full-featured programming language, in particular a scripting language. (This makes it similar in many ways to Matlab and Python)
*  It can be run interactively or as a batch/background job
*  R is being actively developed with ongoing updates/new releases
*  The community of R users make a bunch of tools available for tasks like:
  + graphing
  + advanced/specialized statistical models
  + making websites
  + writing books
* Available for Windows, Mac OS X, and Linux

## Why R?

* R is widely used (statisticians, scientists, social scientists) and has the widest statistical functionality of any software
* R has tools for pharmacometrics! Example: `nlmixr` and `PKPDsim`
* Users add functionality via packages all the time
* R is free and available on all major platforms
* R is very powerful, flexible, and easy to use
* R allows for reproducibility and automating tasks
* R can do essentially anything
* Wide usage helps to improve quality and reduce bugs
* Wide usage means there's a lot of tools available online for help

## Why Not R?

* Other software is better than R at various tasks
* R can be much slower than compiled languages (but is often quite fast with good coding practices!)
* R's packages are only as good as the person who wrote them; no explicit quality control
* R is a sprawling and unstandardized ecosystem

## What are my other options? Get me out of here!

* Python
* Matlab/Octave
* Julia (for pharmacometrics, see `pumas`)
* C/C++
* SAS
* Stata

# Administrative Info

Four part series:

* September 18th
* September 25th
* October 2nd
* October 9th

## Microcredit Program
A microcredit in "R for data science" is available!

*Requirements*:

- Participate in the 4-lecture workshop (so far, great start!)
- Complete the assignment
- Email the assignment to Professor Krzyzanski; wk <AT> buffalo.edu

## Format of course

* Presentation of material, with example code
* Use the chat or speak on microphone to ask questions!
* Mini break-out sessions to try writing your own code

## Course material

* All course material is available on github!
* The course material will also be emailed to you before each session.
* For questions, message me at: jasminehannahhughes AT gmail.com

Take a moment now to open the course material in R Studio.


# The Legal Stuff
- This workshop includes material from a workshop prepared by Chris Paciorek with contributions from Kellie Ottoboni, Nima Hejazi, Rochelle Terman, Chris Krogslund, and Jarrod Millman; originally presented at UC Berkeley (D-Lab, Dept of Statistics).
- Some of this material was drawn from [Jared Knowles R bootcamp](http://jaredknowles.com/r-bootcamp/url).
- You are free to use, modify and redistribute any of this material with or without attribution. If you liked it and use parts of it in the future, please give a call out to the people above and to myself.

